version: "3.9"

services:
  django:
    build: .
    container_name: house-price-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: